apiVersion: batch/v1
kind: CronJob
metadata:
  name: ${APPLICATION_NAME}
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ${APPLICATION_NAME}
              image: ${CONTAINER_IMAGE_TAGGED}
              envFrom:
                - secretRef:
                    name: sendgrid-keepalive-env
